/**
 * Dynamic sitemap for job postings and company profiles.
 *
 * `public/sitemap.xml` (generated by scripts/generate-sitemap.mjs) only lists static
 * pages + blog: job ads and company profiles are never build-time data — they come from
 * a live scrape of the Arca24 feed (see api/jobs.js, api/companies.js, api/_arca24.js) and
 * rotate/expire on their own schedule, so a static list would go stale immediately.
 *
 * This endpoint reuses the same exported fetch/parse primitives those handlers use —
 * it does not re-implement any scraping or HTML parsing.
 *
 * Feed-resilience rules this file follows (see 00_Wiki/job-courier/jobroom-feed-resilience.md):
 *   - never `find(...) || list[0]` — an id/slug is only emitted if actually read from
 *     the feed, there is no placeholder fallback.
 *   - a thin/degraded result is served honestly (a small sitemap), never padded, and is
 *     not cached at the long TTL — so the next crawl can pick up a healthier read.
 */
import {
  isArca24Enabled,
  fetchCompanies as fetchArca24Companies,
  fetchCompanyDetail as fetchArca24CompanyDetail,
  fetchJobs as fetchArca24Jobs,
} from './_arca24.js';
import { parseJobsFromHtml } from './jobs.js';
import { fetchCompanyListHtml, parseCompaniesFromHtml } from './companies.js';
import fetch from 'node-fetch';

const SITE = 'https://www.jobcourier.ch';

// Google's technical cap is 50k URLs/sitemap; we stay far under it — a sitemap this size
// is already generous for a marketplace this scale and keeps the function's request
// budget (one request per company on the Arca24 path) reasonable.
const MAX_JOB_URLS = 800;
const MAX_COMPANY_URLS = 250;

// Same threshold jobs.js uses to call a listing result "healthy" rather than degraded.
const MIN_HEALTHY_JOBS = 10;

const ARCA24_BATCH_SIZE = 12;
const ARCA24_LISTING_PAGES = 5;

const JOBROOM_HEADERS = {
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'Accept-Language': 'it-IT,it;q=0.9,en;q=0.7',
  'Cache-Control': 'no-cache',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120',
  'Referer': 'https://jobroom.jobcourier.ch/',
};
const JOBROOM_LISTING_PAGES = 20;

function escapeXml(value) {
  return String(value).replace(/[<>&'"]/g, (c) => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;',
  }[c]));
}

function buildUrlset(locs) {
  const body = locs.map((loc) => `  <url>\n    <loc>${escapeXml(loc)}</loc>\n  </url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

/**
 * Arca24 path: the "latest jobs" listing pages for recency, then a per-company sweep
 * (using the same fetchCompanyDetail the company-detail page uses) for the ads the
 * listing pages do not reach — the listing is company-ordered, so a handful of pages
 * mostly returns one brand. Mirrors the orchestration api/jobs.js does internally for
 * its own showcase, without duplicating any of its parsing.
 */
async function collectArca24(maxJobs) {
  const companies = await fetchArca24Companies();
  const jobIds = new Set();

  for (const job of await fetchArca24Jobs({ pages: ARCA24_LISTING_PAGES, maxJobs }).catch(() => [])) {
    if (job.jobroom_id) jobIds.add(job.jobroom_id);
  }

  for (let i = 0; i < companies.length && jobIds.size < maxJobs; i += ARCA24_BATCH_SIZE) {
    const batch = companies.slice(i, i + ARCA24_BATCH_SIZE).map((c) =>
      fetchArca24CompanyDetail(c.id, c.slug).then((d) => d.jobs || []).catch(() => [])
    );
    const results = await Promise.all(batch);
    for (const jobs of results) {
      for (const job of jobs) {
        if (job.jobroom_id) jobIds.add(job.jobroom_id);
      }
    }
  }

  return { jobIds: [...jobIds].slice(0, maxJobs), companies };
}

async function fetchJobroomPage(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 6000);
  try {
    const r = await fetch(url, { headers: JOBROOM_HEADERS, signal: ctrl.signal });
    return r.ok ? await r.text() : '';
  } catch {
    return '';
  } finally {
    clearTimeout(timer);
  }
}

/** Legacy jobroom path: walk the paginated search listing until a page comes back empty. */
async function collectJobroom(maxJobs) {
  const [listHtml, ...pages] = await Promise.all([
    fetchCompanyListHtml(),
    ...Array.from({ length: JOBROOM_LISTING_PAGES }, (_, i) => {
      const url = new URL('https://jobroom.jobcourier.ch/job/latest-and-all-job-ads.php');
      url.searchParams.set('language', 'it');
      url.searchParams.set('country', '214');
      url.searchParams.set('page', String(i + 1));
      return fetchJobroomPage(url.toString());
    }),
  ]);

  const companies = parseCompaniesFromHtml(listHtml);
  const jobIds = new Set();
  pages.forEach((html, i) => {
    if (!html || jobIds.size >= maxJobs) return;
    for (const job of parseJobsFromHtml(html, i * 15)) {
      if (job.jobroom_id) jobIds.add(job.jobroom_id);
    }
  });

  return { jobIds: [...jobIds].slice(0, maxJobs), companies };
}

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');

  try {
    const arca24 = await isArca24Enabled();
    const { jobIds, companies } = arca24
      ? await collectArca24(MAX_JOB_URLS)
      : await collectJobroom(MAX_JOB_URLS);

    const companySlugs = companies
      .map((c) => c.slug)
      .filter(Boolean)
      .slice(0, MAX_COMPANY_URLS);

    const locs = [
      ...jobIds.map((id) => `${SITE}/offerta/${id}`),
      ...companySlugs.map((slug) => `${SITE}/azienda/${slug}`),
    ];

    // A thin result is still served — an honest small sitemap beats a fabricated or
    // crashed one — but it is not cached at the long TTL, same reasoning as api/jobs.js's
    // MIN_HEALTHY_JOBS gate: the next crawl should get a chance at a healthier read.
    const healthy = jobIds.length >= MIN_HEALTHY_JOBS;
    if (!healthy) {
      console.warn(`sitemap-jobs: degraded result (${jobIds.length} jobs, ${companySlugs.length} companies) — short TTL.`);
    }
    res.setHeader('Cache-Control', healthy
      ? 's-maxage=1800, stale-while-revalidate=3600'
      : 's-maxage=60, stale-while-revalidate=120');

    res.status(200).send(buildUrlset(locs));
  } catch (error) {
    console.error('Error building jobs sitemap:', error);
    res.setHeader('Cache-Control', 'no-store');
    res.status(500).send(buildUrlset([]));
  }
}
