/**
 * Dynamic sitemap for job postings and company profiles.
 *
 * `public/sitemap.xml` (generated by scripts/generate-sitemap.mjs) only lists static
 * pages + blog: job ads and company profiles are never build-time data — they come from
 * a live scrape of the Arca24 feed (see api/jobs.js, api/companies.js, api/_arca24.js) and
 * rotate/expire on their own schedule, so a static list would go stale immediately.
 *
 * This endpoint reuses the same exported fetch/parse primitives those handlers use —
 * it does not re-implement any scraping or HTML parsing.
 *
 * Feed-resilience rules this file follows (see 00_Wiki/job-courier/jobroom-feed-resilience.md):
 *   - never `find(...) || list[0]` — an id/slug is only emitted if actually read from
 *     the feed, there is no placeholder fallback.
 *   - a thin/degraded result is served honestly (a small sitemap), never padded, and is
 *     not cached at the long TTL — so the next crawl can pick up a healthier read.
 */
import {
  isArca24Enabled,
  fetchCompanies as fetchArca24Companies,
  fetchCompanyDetail as fetchArca24CompanyDetail,
  fetchJobs as fetchArca24Jobs,
} from './_arca24.js';
import { parseJobsFromHtml } from './jobs.js';
import { fetchCompanyListHtml, parseCompaniesFromHtml } from './companies.js';
import { jobs as jobsSnapshot } from './_jobs-snapshot.js';
import { companies as companiesSnapshot } from './_companies-snapshot.js';
import fetch from 'node-fetch';

const SITE = 'https://www.jobcourier.ch';

// Google's technical cap is 50k URLs/sitemap; we stay far under it — a sitemap this size
// is already generous for a marketplace this scale and keeps the function's request
// budget (one request per company on the Arca24 path) reasonable.
const MAX_JOB_URLS = 800;
const MAX_COMPANY_URLS = 250;

// Same threshold jobs.js uses to call a listing result "healthy" rather than degraded.
const MIN_HEALTHY_JOBS = 10;

// How long the live collection (Arca24 batches, or the jobroom listing walk) is allowed to
// run before this endpoint answers from the build-time snapshots instead. Neither
// collectArca24 nor collectJobroom bounds its own upstream calls — _arca24.js has no
// AbortController on this path, unlike fetchJobroomPage's own 6s timeout below — so a slow
// or hanging Arca24 response can otherwise run this function well past what a crawler is
// willing to wait, which reads to it as "no sitemap" (see 00_Wiki/job-courier/
// jobroom-feed-resilience.md for prior forms of this same upstream's flakiness). Same
// race/stand-in shape as api/companies.js's FAST_ANSWER_MS.
const FAST_ANSWER_MS = 8000;

const PENDING = Symbol('pending');

/** Sitemap entries built from the build-time snapshots — no live fetch, so no lastmod. */
function snapshotFallback(maxJobs) {
  const jobIds = jobsSnapshot.map((j) => j.id).filter(Boolean).slice(0, maxJobs);
  return { jobIds, jobDates: new Map(), companies: companiesSnapshot };
}

const ARCA24_BATCH_SIZE = 12;
const ARCA24_LISTING_PAGES = 3;

const JOBROOM_HEADERS = {
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'Accept-Language': 'it-IT,it;q=0.9,en;q=0.7',
  'Cache-Control': 'no-cache',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120',
  'Referer': 'https://jobroom.jobcourier.ch/',
};
const JOBROOM_LISTING_PAGES = 12;

function escapeXml(value) {
  return String(value).replace(/[<>&'"]/g, (c) => ({
    '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;',
  }[c]));
}

function buildUrlset(entries) {
  const body = entries.map(({ loc, lastmod }) => {
    const lm = lastmod ? `\n    <lastmod>${escapeXml(lastmod)}</lastmod>` : '';
    return `  <url>\n    <loc>${escapeXml(loc)}</loc>${lm}\n  </url>`;
  }).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

/**
 * The feed's own "published" label, in whatever loose day-month-year shape the portal
 * happens to render it ("15/08/2026", "15/08/2026 Nuovo!", dot- or dash-separated). Only
 * emitted as `<lastmod>` when it parses to a real calendar date — Google explicitly warns
 * against a guessed or constant lastmod, so a date we can't trust is better left off than
 * fabricated.
 */
function parsePublishedAt(raw) {
  const m = String(raw ?? '').match(/(\d{1,2})[./-](\d{1,2})[./-](\d{4})/);
  if (!m) return null;
  const [, d, mo, y] = m;
  const iso = `${y}-${mo.padStart(2, '0')}-${d.padStart(2, '0')}`;
  return Number.isNaN(new Date(`${iso}T00:00:00Z`).getTime()) ? null : iso;
}

/**
 * Arca24 path: the "latest jobs" listing pages for recency, then a per-company sweep
 * (using the same fetchCompanyDetail the company-detail page uses) for the ads the
 * listing pages do not reach — the listing is company-ordered, so a handful of pages
 * mostly returns one brand. Mirrors the orchestration api/jobs.js does internally for
 * its own showcase, without duplicating any of its parsing.
 */
async function collectArca24(maxJobs) {
  const companies = await fetchArca24Companies();
  const jobDates = new Map();

  for (const job of await fetchArca24Jobs({ pages: ARCA24_LISTING_PAGES, maxJobs }).catch(() => [])) {
    if (job.jobroom_id && !jobDates.has(job.jobroom_id)) {
      jobDates.set(job.jobroom_id, parsePublishedAt(job.published_at));
    }
  }

  for (let i = 0; i < companies.length && jobDates.size < maxJobs; i += ARCA24_BATCH_SIZE) {
    const batch = companies.slice(i, i + ARCA24_BATCH_SIZE).map((c) =>
      fetchArca24CompanyDetail(c.id, c.slug).then((d) => d.jobs || []).catch(() => [])
    );
    const results = await Promise.all(batch);
    for (const jobs of results) {
      for (const job of jobs) {
        if (job.jobroom_id && !jobDates.has(job.jobroom_id)) {
          jobDates.set(job.jobroom_id, parsePublishedAt(job.published_at));
        }
      }
    }
  }

  return { jobIds: [...jobDates.keys()].slice(0, maxJobs), jobDates, companies };
}

async function fetchJobroomPage(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 6000);
  try {
    const r = await fetch(url, { headers: JOBROOM_HEADERS, signal: ctrl.signal });
    return r.ok ? await r.text() : '';
  } catch {
    return '';
  } finally {
    clearTimeout(timer);
  }
}

/** Legacy jobroom path: walk the paginated search listing until a page comes back empty. */
async function collectJobroom(maxJobs) {
  const [listHtml, ...pages] = await Promise.all([
    fetchCompanyListHtml(),
    ...Array.from({ length: JOBROOM_LISTING_PAGES }, (_, i) => {
      const url = new URL('https://jobroom.jobcourier.ch/job/latest-and-all-job-ads.php');
      url.searchParams.set('language', 'it');
      url.searchParams.set('country', '214');
      url.searchParams.set('page', String(i + 1));
      return fetchJobroomPage(url.toString());
    }),
  ]);

  const companies = parseCompaniesFromHtml(listHtml);
  const jobDates = new Map();
  pages.forEach((html, i) => {
    if (!html || jobDates.size >= maxJobs) return;
    for (const job of parseJobsFromHtml(html, i * 15)) {
      if (job.jobroom_id && !jobDates.has(job.jobroom_id)) {
        jobDates.set(job.jobroom_id, parsePublishedAt(job.published_at));
      }
    }
  });

  return { jobIds: [...jobDates.keys()].slice(0, maxJobs), jobDates, companies };
}

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');

  try {
    const arca24 = await isArca24Enabled();
    const work = arca24 ? collectArca24(MAX_JOB_URLS) : collectJobroom(MAX_JOB_URLS);

    // Race the live collection against a fast-answer budget so a slow/hanging upstream
    // cannot stall this response past what a crawler will wait for. The live run is left
    // to keep going after the budget fires — there is nothing here to hand its result to
    // once we've answered, so it is just left to settle and its rejection swallowed.
    let timer;
    const budget = new Promise((resolve) => { timer = setTimeout(() => resolve(PENDING), FAST_ANSWER_MS); });
    let collected;
    try {
      collected = await Promise.race([work, budget]);
    } finally {
      clearTimeout(timer);
    }

    let usedFallback = false;
    if (collected === PENDING) {
      usedFallback = true;
      collected = snapshotFallback(MAX_JOB_URLS);
      work.catch(() => {});
    }

    const { jobIds, jobDates, companies } = collected;

    const companySlugs = companies
      .map((c) => c.slug)
      .filter(Boolean)
      .slice(0, MAX_COMPANY_URLS);

    const locs = [
      ...jobIds.map((id) => ({ loc: `${SITE}/offerta/${id}`, lastmod: jobDates.get(id) || null })),
      // No reliable per-company "last changed" signal in the feed — omitted rather than
      // guessed, same reasoning as parsePublishedAt above.
      ...companySlugs.map((slug) => ({ loc: `${SITE}/azienda/${slug}`, lastmod: null })),
    ];

    // A thin result is still served — an honest small sitemap beats a fabricated or
    // crashed one — but it is not cached at the long TTL, same reasoning as api/jobs.js's
    // MIN_HEALTHY_JOBS gate: the next crawl should get a chance at a healthier read. A
    // snapshot fallback is always treated as degraded, regardless of its size, so the next
    // request still gets a shot at the live path.
    const healthy = !usedFallback && jobIds.length >= MIN_HEALTHY_JOBS;
    if (!healthy) {
      console.warn(`sitemap-jobs: degraded result (${jobIds.length} jobs, ${companySlugs.length} companies, fallback=${usedFallback}) — short TTL.`);
    }
    res.setHeader('Cache-Control', healthy
      ? 's-maxage=3600, stale-while-revalidate=7200'
      : 's-maxage=60, stale-while-revalidate=120');

    res.status(200).send(buildUrlset(locs));
  } catch (error) {
    console.error('Error building jobs sitemap:', error);
    res.setHeader('Cache-Control', 'no-store');
    res.status(500).send(buildUrlset([]));
  }
}
